use axum::http::header;
use axum::response::IntoResponse;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::audio::AudioFormat;
use crate::server::schema::{
    DynamicVoiceObject, ErrorDetail, ErrorResponse, HealthResponse, ModelListResponse, ModelObject,
    SpeechRequest, StreamFormat, VoiceListResponse, VoiceObject,
};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::server::routes::create_speech,
        crate::server::routes::list_models,
        crate::server::routes::list_voices,
        crate::server::routes::health_check,
    ),
    components(
        schemas(
            SpeechRequest,
            DynamicVoiceObject,
            AudioFormat,
            StreamFormat,
            ModelObject,
            ModelListResponse,
            VoiceObject,
            VoiceListResponse,
            ErrorDetail,
            ErrorResponse,
            HealthResponse,
        )
    ),
    modifiers(&SecurityAddon),
    info(
        title = "GPT-SoVITS Pure Rust Inference Engine & OpenAI TTS API",
        version = "0.1.0",
        description = "High-performance pure Rust inference engine and 100% OpenAI-compatible TTS server for GPT-SoVITS (supporting v1, v2, v2Pro, v2ProPlus, v3, and v4 models).",
        license(name = "MIT or Apache-2.0")
    ),
    servers(
        (url = "/", description = "Current Server Instance")
    )
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearerAuth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("API Key")
                        .description(Some("Bearer authentication token configured in config.toml"))
                        .build(),
                ),
            );
        }
    }
}

/// Handler for GET /openapi.json (auto-generated by utoipa macro at compile time)
pub async fn openapi_json() -> impl IntoResponse {
    let spec = ApiDoc::openapi();
    (
        [(header::CONTENT_TYPE, "application/json; charset=utf-8")],
        spec.to_pretty_json().unwrap_or_else(|_| "{}".to_string()),
    )
}
